# Generated by Django 6.0.6 on 2026-07-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Main photo shown on the project card (optional). Recommended: 800×500px or larger.', null=True, upload_to='projects/'),
        ),
    ]
